# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions
name: Build and deploy Python app to Azure Web App - lcrbchat
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: read #This is required for actions/checkout
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # Skip virtual environment and dependency installation
      # Let Azure handle this during deployment
      
      - name: Zip artifact for deployment
        run: |
          # Only package the necessary application files
          Remove-Item -Recurse -Force venv -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force antenv -ErrorAction SilentlyContinue
          Remove-Item -Force output.tar.gz -ErrorAction SilentlyContinue
          Compress-Archive -Path code\* -DestinationPath release.zip -Force
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip
  deploy:
    runs-on: self-hosted
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app
      - name: Unzip artifact for deployment
        run: Expand-Archive -Path release.zip -DestinationPath . -Force
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3C317EBFCF374FF6AC76A7DA9E23F83E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5C5ECBB906FA4E7986CBD5BC76D40B86 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4074A50AAF374676B6F495A86524313D }}
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'lcrbchat'
          slot-name: 'Production'
